//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSmrn.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeYuliya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeYuliya()
        {
            this.AppointmentYuliya = new HashSet<AppointmentYuliya>();
        }
    
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string Phone { get; set; }
        public int IDDepartment { get; set; }
        public int IDPost { get; set; }
        public int IDGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentYuliya> AppointmentYuliya { get; set; }
        public virtual DepartmentYuliya DepartmentYuliya { get; set; }
        public virtual GenderYuliya GenderYuliya { get; set; }
        public virtual PostYuliya PostYuliya { get; set; }
    }
}
